name: Build

on:
  push:
    paths:
      - src/**

env:
  BUILD_TYPE: MinSizeRel
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        shell: bash
        run: |
          sudo apt-get install build-essential ninja-build cmake libgl1-mesa-dev qt6-base-dev -y
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B "./cmake-build-minsizerel"
          cmake --build ./cmake-build-minsizerel --target minipro-gui -- -j 2
