name: Build MacOS

on:
  workflow_dispatch:
    workflow_run:
      workflows: [ "Build MacOS" ]
  push:
    branches:
      - 'master'
    paths:
      - src/**
  schedule:
    - cron:  '0 0 1 * *'

env:
  BUILD_TYPE: MinSizeRel

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build MacOS
        shell: bash
        run: |
          brew install ninja cmake qt
          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B "./cmake-build-${BUILD_TYPE}"
          cmake --build ./cmake-build-${BUILD_TYPE} --target minipro-gui -- -j 2
