name: Unit Tests

on:
  workflow_dispatch:
    workflow_run:
      workflows: [ "Unit Tests" ]
  push:
    branches:
      - 'master'
    paths:
      - src/**
      - tests/**
  schedule:
    - cron:  '0 0 1 * *'

env:
  BUILD_TYPE: Debug

jobs:
  Tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Tests
        shell: bash
        run: |
          brew install ninja cmake qt minipro
          cd tests
          ./run_tests.sh
