name: Unit Tests

on:
  push:
    branches:
      - 'master'
    paths:
      - tests/**
  schedule:
    - cron:  '0 0 1 * *'

env:
  BUILD_TYPE: Debug

jobs:
  Ubuntu:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Tests
        shell: bash
        run: |
          brew install ninja cmake qt
          cd tests
          ./run_tests.sh