name: Unit Tests

on:
  push:
    branches:
      - 'master'
    paths:
      - tests/**
  schedule:
    - cron:  '0 0 1 * *'

env:
  BUILD_TYPE: Debug

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Ubuntu
        shell: bash
        run: |
          sudo apt-get install build-essential ninja-build cmake libgl1-mesa-dev qt6-base-dev -y
          cd tests
          ./run_tests.sh