name: Build Ubuntu

on:
  push:
    branches:
      - 'master'
#    paths:
#      - src/**
  schedule:
    - cron:  '0 0 1 * *'

env:
  BUILD_TYPE: MinSizeRel

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Ubuntu
        shell: bash
        run: |
          sudo apt-get install build-essential ninja-build cmake libgl1-mesa-dev qt6-base-dev -y
          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B "./cmake-build-${BUILD_TYPE}"
          cmake --build ./cmake-build-${BUILD_TYPE} --target minipro-gui -- -j 2
